accounts/urls.py
from django.urls import path

from .views import (RegistrationView, LogInView, LogOutView, UserCreationView, UserDetailView,
                    WorkerCreationView, WorkerDetailView, WorkerListView, UserListView, UserChangePasswordView)

app_name = 'accounts'


urlpatterns = [
    path('login/', LogInView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),

    path('user-list/', UserListView.as_view(), name='user_list'),
    path('user-creation/', UserCreationView.as_view(), name='user_creation'),
    path('user-detail/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('user-change-password/<int:pk>/', UserChangePasswordView.as_view(), name='user_change_password'),

    path('worker-list/', WorkerListView.as_view(), name='worker_list'),
    path('worker-creation/', WorkerCreationView.as_view(), name='worker_creation'),
    path('worker-detail/<int:pk>/', WorkerDetailView.as_view(), name='worker_detail'),
]

affairs/urls.py
from django.urls import path

from reports.urls import urlpatterns as main_repo_urls
from .views import (home, MonthCreationView, MonthDetailView, MonthListView, MonthDayInlineView,
                    ActivityCreationView, ActivityDetailView, ActivityDeleteView,  ActivityListView,
                    LocationCreationView, LocationDetailView, LocationDeleteView, LocationListView,
                    VacationsCreationView, VacationsDetailView, VacationsListView,
                    validate_month_uniqueness)


app_name = 'affairs'


urlpatterns = [
    path('', home, name='home'),
    *main_repo_urls,

    path('month-list/', MonthListView.as_view(), name='month_list'),
    path('month-creation/', MonthCreationView.as_view(), name='month_creation'),
    path('month-detail/<int:pk>/', MonthDetailView.as_view(), name='month_detail'),
    path('month-day-inline/<int:pk>', MonthDayInlineView.as_view(), name='month_day_inline'),

    path('activity-list/', ActivityListView.as_view(), name='activity_list'),
    path('activity-creation/', ActivityCreationView.as_view(), name='activity_creation'),
    path('activity-detail/<int:pk>/', ActivityDetailView.as_view(), name='activity_detail'),
    path('activity-delete/<int:pk>/', ActivityDeleteView.as_view(), name='activity_delete'),

    path('location-list/', LocationListView.as_view(), name='location_list'),
    path('location-creation/', LocationCreationView.as_view(), name='location_creation'),
    path('location-detail/<int:pk>/', LocationDetailView.as_view(), name='location_detail'),
    path('location-delete/<int:pk>/', LocationDeleteView.as_view(), name='location_delete'),

    path('vacations_list/', VacationsListView.as_view(), name='vacations_list'),
    path('vacations-creation/', VacationsCreationView.as_view(), name='vacations_creation'),
    path('vacations-detail/<int:pk>/', VacationsDetailView.as_view(), name='vacations_detail'),

    path('month_uniqueness/', validate_month_uniqueness, name='month_uniqueness'),
]

reports/urls.py
from django.urls import path
from .views import (MultiWorkerReportView, AccommodationReportView, MultiWorkerReportPrintView,
                    SingleMonthReportView, SingleMonthReportPrintView, LocationReportView)


urlpatterns = [
    path('multi-worker-report/', MultiWorkerReportView.as_view(), name='multi_worker_report'),
    path('multi-worker-report-print/', MultiWorkerReportPrintView.as_view(), name='multi_worker_report_print'),

    path('single-month-report/', SingleMonthReportView.as_view(), name='single_month_report'),
    path('single-month-report-print/<int:pk>/', SingleMonthReportPrintView.as_view(), name='single_month_report_print'),

    path('accommodation-report/', AccommodationReportView.as_view(), name='accommodation_report'),

    path('location-report/', LocationReportView.as_view(), name='location_report'),
]

techno_art/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('affairs.urls', namespace='affairs')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/css.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'css/tooplate-style.css' %}">

templates/base/footer.html
<footer id="footer" data-stellar-background-ratio="0.5">
      <div class="container">
           <div class="row">
                <div class="copyright-text col-md-12 col-sm-12">
                     <div class="col-md-6 col-sm-6">
                          <p>Copyright &copy; 2021 -by <a href="mailto: moha.gamal@nu.edu.eg">© Mohamed Gamal</a></p>
                     </div>
                </div>
           </div>
      </div>
 </footer>

templates/base/js.html
{% load static %}

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/smoothscroll.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

templates/base/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="container-fluid p-0">
            <div class="alert {% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible"
                 style="{% if forloop.first %}margin-top: 100px;{% endif %} direction: rtl"  role="alert">
                <p>{{ message }}</p>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
    {% endfor %}
{% endif %}

templates/base/nav.html
{% load static %}
<section class="navbar custom-navbar navbar-fixed-top" role="navigation" style="background-color:black; padding-bottom: 10px; margin-bottom: 30px;">
      <div class="container" >
           <div class="navbar-header">
                <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                     <span class="icon icon-bar"></span>
                     <span class="icon icon-bar"></span>
                     <span class="icon icon-bar"></span>
                </button>
                <!-- lOGO TEXT HERE -->
                <a href="{% url 'affairs:home' %}" class="navbar-brand" style="padding-top: 0px;"><img src="{% static 'images/logo_white.jpeg' %}" style="height: 50px; width:45px"></a>
           </div>
           <!-- MENU LINKS -->
           <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                     {% if request.user.is_authenticated %}
                            <li><a href="{% url 'accounts:logout' %}" class="smoothScroll">تسجيل خروج</a></li>
                            <li><a href="{% url 'affairs:location_report' %}" class="smoothScroll">المواقع</a></li>
                            <li><a id="add_attendance" class="smoothScroll">الرواتب</a></li>
                            <li><a href="{% url 'accounts:worker_list' %}" class="smoothScroll">الموظفين</a></li>
                            <li><a href="{% url 'affairs:accommodation_report' %}" class="smoothScroll">الاقامة</a></li>
                            <li><a href="{% url 'affairs:month_creation' %}" class="smoothScroll">الحضور واالنصراف</a></li>
                     {% else %}
                         <li><a href="{% url 'accounts:login' %}" class="smoothScroll">تسجيل دخول</a></li>
                     {% endif %}
                         <li><a href="{% url 'affairs:home' %}" class="smoothScroll"> الرئيسية</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                     <li> <p style="font-family:Fantasy; color: red;  font-size: 30px; padding-top: 10px;"> تكنو ارت للمقاولات</p></li>
                </ul>
           </div>
      </div>
 </section>