affairs/urls.py
from django.urls import path

from reports.urls import urlpatterns as main_repo_urls
from .views import (home, MonthCreationView, MonthDetailView, MonthListView, MonthDayInlineView,
                    ActivityCreationView, ActivityDetailView, ActivityDeleteView,  ActivityListView,
                    LocationCreationView, LocationDetailView, LocationDeleteView, LocationListView,
                    VacationsCreationView, VacationsDetailView, VacationsListView,
                    validate_month_uniqueness)


app_name = 'affairs'


urlpatterns = [
    path('', home, name='home'),
    *main_repo_urls,

    path('month-list/', MonthListView.as_view(), name='month_list'),
    path('month-creation/', MonthCreationView.as_view(), name='month_creation'),
    path('month-detail/<int:pk>/', MonthDetailView.as_view(), name='month_detail'),
    path('month-day-inline/<int:pk>', MonthDayInlineView.as_view(), name='month_day_inline'),

    path('activity-list/', ActivityListView.as_view(), name='activity_list'),
    path('activity-creation/', ActivityCreationView.as_view(), name='activity_creation'),
    path('activity-detail/<int:pk>/', ActivityDetailView.as_view(), name='activity_detail'),
    path('activity-delete/<int:pk>/', ActivityDeleteView.as_view(), name='activity_delete'),

    path('location-list/', LocationListView.as_view(), name='location_list'),
    path('location-creation/', LocationCreationView.as_view(), name='location_creation'),
    path('location-detail/<int:pk>/', LocationDetailView.as_view(), name='location_detail'),
    path('location-delete/<int:pk>/', LocationDeleteView.as_view(), name='location_delete'),

    path('vacations_list/', VacationsListView.as_view(), name='vacations_list'),
    path('vacations-creation/', VacationsCreationView.as_view(), name='vacations_creation'),
    path('vacations-detail/<int:pk>/', VacationsDetailView.as_view(), name='vacations_detail'),

    path('month_uniqueness/', validate_month_uniqueness, name='month_uniqueness'),
]

techno_art/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('affairs.urls', namespace='affairs')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

affairs/forms.py
from django import forms
from django.forms.models import inlineformset_factory

from accounts.models import Worker
from reports.forms import BaseForm
from .widgets import CustomCheckboxInput
from .utils import MONTHS_NAMES, YEARS_NUMBERS
from .models import Month, Location, Activity, Vacations,  Day


class MonthUpdateForm(forms.ModelForm):

    class Meta:
        model = Month
        fields = ('worker', 'activity', 'month', 'year')
        labels = {
            'activity': 'النشاط',
            'worker': 'موظف'
        }
        widgets = {
            'worker': forms.Select(attrs={'class': 'form-control', 'required': True}),
            'activity': forms.Select(attrs={'class': 'form-control'}),
            'month': forms.Select(attrs={'class': 'form-control'}),
            'year':  forms.Select(attrs={'class': 'form-control'}),
        }


class MonthCreationForm(MonthUpdateForm):
    location = forms.ModelChoiceField(queryset=Location.objects.all(), label='الموقع',
                                      help_text='سيتم اضافة الموقع لكل يوم في الشهر تلقائيا',
                                      widget=forms.Select(attrs={'class': 'form-control'}), required=True)

    def clean_location(self):
        location_id = self.cleaned_data.get('location')
        if location_id == "---------":
            raise forms.ValidationError('هذا الحقل مطلوب')
        return location_id


class MonthListFrom(BaseForm):
    worker = forms.ModelChoiceField(queryset=Worker.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}),
                                    label='العامل')
    activity = forms.ModelChoiceField(queryset=Activity.objects.all(),
                                      widget=forms.Select(attrs={'class': 'form-control'}), label='النشاط', required=False)
    month = forms.ChoiceField(choices=MONTHS_NAMES, label='الشهر', widget=forms.Select(attrs={'class': 'form-control'}),
                              required=False)
    year = forms.ChoiceField(choices=YEARS_NUMBERS, label='السنة', widget=forms.Select(attrs={'class': 'form-control'}),
                             required=False)


class ActivityCreationForm(forms.ModelForm):

    class Meta:
        model = Activity
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }


class ActivityListForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label='النشاط')


class LocationCreationForm(forms.ModelForm):

    class Meta:
        model = Location
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }


class LocationListForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label='الموقع')


class DayUpdateForm(forms.ModelForm):
    field_order = ['day_number', 'day_name', 'location', 'attendance', 'extra_work_hours', 'deduction', 'rewards', 'loans']
    day_name = forms.CharField(required=False, label="اليوم")

    def __init__(self, *args, **kwargs):
        super(DayUpdateForm, self).__init__(*args, **kwargs)
        day_name_field = self.fields.get('day_name')
        day_name_field.widget.attrs = {'class': 'form-control', 'readonly': True}
        day_name_field.initial = self.instance.get_day_name()

    class Meta:
        model = Day
        fields = '__all__'
        widgets = {
            'location': forms.Select(attrs={'class': 'form-control'}),
            'attendance': CustomCheckboxInput(attrs={'class': 'custom-control-input'}),
            'day_number':  forms.NumberInput(attrs={'class': 'form-control', 'readonly': True, 'style': "width: 50px"}),
            'extra_work_hours': forms.NumberInput(attrs={'class': 'form-control'}),
            'deduction': forms.NumberInput(attrs={'class': 'form-control'}),
            'rewards': forms.NumberInput(attrs={'class': 'form-control'}),
            'loans': forms.NumberInput(attrs={'class': 'form-control'}),
        }


class VacationsCreationForm(forms.ModelForm):

    class Meta:
        model = Vacations
        fields = '__all__'
        widgets = {
            'worker': forms.Select(attrs={'class': 'form-control'}),
            'reason': forms.TextInput(attrs={'class': 'form-control'}),
            'start_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'end_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
        }


class VacationsListForm(forms.Form):
    worker = forms.ModelChoiceField(queryset=Worker.objects.all(),
                                    widget=forms.Select(attrs={'class': 'form-control'}), label='العامل')
    start_date = forms.DateField(widget=forms.SelectDateWidget(attrs={'class': 'form-control', 'type': 'date'}),
                                 label='من', required=False)
    end_date = forms.DateField(widget=forms.SelectDateWidget(attrs={'class': 'form-control', 'type': 'date'}),
                               label='الي', required=False)


MonthDaysInlineFormset = inlineformset_factory(Month, Day, form=DayUpdateForm, extra=0, can_delete=False)

affairs/views.py
from django.urls import reverse_lazy
from django.shortcuts import render, reverse, redirect
from django.http import HttpResponseRedirect, JsonResponse
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import CreateView, UpdateView, DeleteView, FormView
from django.contrib.auth.backends import get_user_model
from django.contrib.messages.views import SuccessMessageMixin

from .decorators import ajax_get_required
from accounts.decorators import AdminAuthMixIn
from reports.utils import is_valid_choice
from reports.base_views import BaseSearchList
from .models import Month, Location, Activity, Vacations, Day
from .forms import (MonthCreationForm, MonthUpdateForm, ActivityCreationForm, LocationCreationForm, DayUpdateForm,
                    VacationsCreationForm, MonthListFrom, ActivityListForm, LocationListForm, VacationsListForm,
                    MonthDaysInlineFormset)


User = get_user_model()


def home(request):
    return render(request, 'home.html')


class MonthCreationView(SuccessMessageMixin, CreateView, AdminAuthMixIn):
    model = Month
    form_class = MonthCreationForm
    template_name = 'affairs/creation/month.html'
    success_message = 'تم ادخال البيانات بطريقة صحيحة'
    extra_context = {'title': 'انشاء شهر جديد'}

    def form_valid(self, form):
        month = form.save()
        location = form.cleaned_data.get('location')
        Day.objects.filter(month=month).update(location=location)
        return redirect(reverse('affairs:month_day_inline', kwargs={'pk': month.pk}))


class MonthDetailView(UpdateView, AdminAuthMixIn):
    model = Month
    form_class = MonthUpdateForm
    template_name = 'affairs/update/month.html'
    extra_context = {'title': 'تعديل الشهر'}
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['days'] = Day.objects.filter(month=self.get_object())
        return context


class MonthDayInlineView(SuccessMessageMixin, SingleObjectMixin, FormView, AdminAuthMixIn):
    model = Month
    form_class = MonthDaysInlineFormset
    template_name = 'affairs/update/month_day_inline.html'
    success_message = 'تم التعديل بنجاح'
    extra_context = {
        'title': 'تسجيل الحضور'
    }
    context_object_name = 'month'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=self.model.objects.all())
        return super().post(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=self.model.objects.all())
        return super().get(request, *args, **kwargs)

    def get_form(self, form_class=None):
        return self.form_class(**self.get_form_kwargs(), instance=self.object)

    def get_context_data(self, **kwargs):
        if 'form' not in kwargs:
            kwargs['form'] = self.get_form()
        return super().get_context_data(**kwargs)

    def get_success_url(self):
        return reverse('affairs:single_month_report_print', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect(self.get_success_url())


class MonthListView(BaseSearchList):
    model = Month
    form_class = MonthListFrom
    context_object_name = 'months'
    template_name = 'affairs/list/month.html'
    extra_context = {
        'title': 'الشهر'
    }

    def get_form_queryset(self, form, queryset):
        worker = form.cleaned_data.get('worker')
        activity = form.cleaned_data.get('activity')
        month = form.cleaned_data.get('month')
        year = form.cleaned_data.get('year')
        if worker:
            queryset = queryset.filter(worker=worker)
        if activity:
            queryset = queryset.filter(activity=activity)
        if is_valid_choice(month):
            queryset = queryset.filter(month=month)
        if is_valid_choice(year):
            queryset = queryset.filter(year=year)
        return queryset


class ActivityCreationView(SuccessMessageMixin, CreateView):
    form_class = ActivityCreationForm
    template_name = 'affairs/creation/base.html'
    success_message = 'تم ادخال البيانات بطريقة صحيحة'
    extra_context = {'title': 'انشاء نشاط  جديد'}

    def form_valid(self, form):
        activity = form.save()
        return redirect(reverse('affairs:activity_detail', kwargs={'pk': activity.pk}))


class ActivityDetailView(UpdateView):
    model = Activity
    form_class = ActivityCreationForm
    template_name = 'affairs/update/base.html'
    extra_context = {'title': 'تعديل النشاط'}
    success_url = '/'


class ActivityDeleteView(DeleteView, SuccessMessageMixin):
    model = Activity
    template_name = 'affairs/delete/activity.html'
    success_message = 'تم الحذف بنجاح'
    success_url = reverse_lazy("affairs:activity_list")
    extra_context = {'title': 'جذف نشاط'}


class ActivityListView(BaseSearchList):
    model = Activity
    form_class = ActivityListForm
    context_object_name = 'activities'
    template_name = 'affairs/list/activity.html'
    extra_context = {
        'title': 'النشاطات'
    }

    def get_form_queryset(self, form, queryset):
        name = form.cleaned_data.get('name')
        if name:
            queryset = queryset.filter(name__icontains=name)
        return queryset


class LocationCreationView(SuccessMessageMixin, CreateView):
    form_class = LocationCreationForm
    template_name = 'affairs/creation/base.html'
    success_message = 'تم ادخال البيانات بطريقة صحيحة'
    extra_context = {'title': 'انشاء  موقع جديد'}

    def form_valid(self, form):
        location = form.save()
        return redirect(reverse('affairs:location_detail', kwargs={'pk': location.pk}))


class LocationDeleteView(DeleteView, SuccessMessageMixin):
    model = Location
    template_name = 'affairs/delete/location.html'
    success_message = 'تم الحذف بنجاح'
    success_url = reverse_lazy('affairs:location_list')
    extra_context = {'title': 'حذف الموقع'}


class LocationDetailView(UpdateView):
    model = Location
    form_class = LocationCreationForm
    template_name = 'affairs/update/base.html'
    extra_context = {'title': 'تعديل الموقع'}
    success_url = '/'


class LocationListView(BaseSearchList):
    model = Location
    form_class = LocationListForm
    context_object_name = 'locations'
    template_name = 'affairs/list/location.html'
    extra_context = {
        'title': 'المواقع'
    }

    def get_form_queryset(self, form, queryset):
        name = form.cleaned_data.get('name')
        if name:
            queryset = queryset.filter(name__icontains=name)
        return queryset


class VacationsCreationView(SuccessMessageMixin, CreateView):
    form_class = VacationsCreationForm
    template_name = 'affairs/creation/base.html'
    success_message = 'تم ادخال البيانات بطريقة صحيحة'
    extra_context = {'title': 'انشاء اجازة جديدة'}

    def form_valid(self, form):
        vacations = form.save()
        return redirect(reverse('affairs:vacations_detail', kwargs={'pk': vacations.pk}))


class VacationsDetailView(UpdateView):
    model = Vacations
    form_class = VacationsCreationForm
    template_name = 'accounts/update/user.html'
    extra_context = {'title': 'تعديل اجازة '}
    success_url = '/'


class VacationsListView(BaseSearchList):
    model = Vacations
    form_class = VacationsListForm
    context_object_name = 'vacations'
    template_name = 'affairs/list/vacations.html'
    extra_context = {
        'title': 'الاجازات'
    }

    def get_form_queryset(self, form, queryset):
        worker = form.cleaned_data.get('worker')
        start_date = form.cleaned_data.get('start_date')
        end_date = form.cleaned_data.get('end_date')
        if worker:
            queryset = queryset.filter(worker=worker)
        if start_date:
            queryset = queryset.filter(start_date__gte=start_date)
        if end_date:
            queryset = queryset.filter(start_date__lte=end_date)
        return queryset


@ajax_get_required
def validate_month_uniqueness(request):
    worker_id = request.GET.get('worker_id')
    month = request.GET.get('month')
    year = request.GET.get('year')
    _month = Month.objects.filter(worker__id=worker_id, month=month, year=year)
    if _month.exists():
        return JsonResponse({
            'month_id': _month.first().id,
            'is_existed': True
        })
    return JsonResponse({'is_existed': False})

templates/affairs/list/activity.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    <br><h4> الشهور</h4>
  <form method="GET" class="contact-form" style="width:45%; align:center; margin: 0 auto; margin-top:35px;  direction: rtl;">
       <h4 style="text-align:center;">{{ title }}</h4>
       {{ form.as_p }}
       <div class="d-grid" style="margin-top:10px; ">
           <button class="btn btn-dark btn-lg " id="submitButton" type="submit">بحث</button>
           <a href="{% url 'affairs:activity_creation' %}" class="btn btn-dark btn-lg" style="direction: ltr; display: inline; left: 10px;">
               اضافة
               <img src="{% static 'admin/img/icon-addlink.svg' %}" style="height10px; width10px">
           </a>
       </div>
    </form>

    {% if activities %}
    <table class="table table-striped" style="width:45%; align:center; margin: 0 auto; margin-top:65px;  direction: rtl;">
      <thead>
        <tr>
          <td>الاسم</td>
          <td>المزيد</td>
          <td>حذف</td>
        </tr>
      </thead>
      <tbody>
      {% for activity in activities %}
        <tr>
          <td scope="row">{{ activity.name }}</td>
          <td><a href="{{ activity.get_absolute_url }}"> المزيد </a></td>
          <td><a href="{% url 'affairs:activity_delete' activity.id %}"> حذف </a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    {% endif %}

{% endblock %}

templates/affairs/list/location.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    <br><h4> الشهور</h4>
  <form method="GET" class="contact-form" style="width:45%; align:center; margin: 0 auto; margin-top:35px;  direction: rtl;">
       <h4 style="text-align:center;">{{ title }}</h4>
       {{ form.as_p }}
       <div class="d-grid" style="margin-top:10px; ">
           <button class="btn btn-dark btn-lg " id="submitButton" type="submit">بحث</button>
           <a href="{% url 'affairs:location_creation' %}" class="btn btn-dark btn-lg" style="direction: ltr; display: inline; left: 10px;">
               اضافة
               <img src="{% static 'admin/img/icon-addlink.svg' %}" style="height10px; width10px">
           </a>
       </div>
    </form>

    {% if locations %}
    <table class="table table-striped" style="width:45%; align:center; margin: 0 auto; margin-top:65px;  direction: rtl;">
      <thead>
        <tr>
          <td>الاسم</td>
          <td>المزيد</td>
          <td>حذف</td>
        </tr>
      </thead>
      <tbody>
      {% for location in locations %}
        <tr>
          <td scope="row">{{ location.name }}</td>
          <td><a href="{{ location.get_absolute_url }}"> المزيد </a></td>
          <td><a href="{% url 'affairs:location_delete' location.id %}"> حذف </a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    {% endif %}

{% endblock %}

templates/affairs/list/month.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    <br><h4> الشهور</h4>
  <form method="GET" class="contact-form" style="width:45%; align:center; margin: 0 auto; margin-top:35px;  direction: rtl;">
       <h4 style="text-align:center;">{{ title }}</h4>
       {{ form.as_p }}
       <div class="d-grid" style="margin-top:10px; ">
           <button class="btn btn-dark btn-lg " id="submitButton" type="submit">بحث</button>
           <a href="{% url 'affairs:month_creation' %}" class="btn btn-dark btn-lg" style="direction: ltr; display: inline; left: 10px;">
               اضافة
               <img src="{% static 'admin/img/icon-addlink.svg' %}" style="height10px; width10px">
           </a>
       </div>
    </form>

    {% if months %}
    <table class="table table-striped" style="width:45%; align:center; margin: 0 auto; margin-top:65px;  direction: rtl;">
      <thead>
        <tr>
          <td>الاسم</td>
          <td>النشاط</td>
          <td>الشهر</td>
          <td>السنة</td>
          <td>المزيد</td>
        </tr>
      </thead>
      <tbody>
      {% for month in months %}
        <tr>
          <td scope="row">{{ month }}</td>
          <td>{{ month.activity }}</td>
          <td>{{ month.month }}</td>
          <td>{{ month.year }}</td>
          <td><a href="{{ month.get_absolute_url }}"> المزيد </a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    {% endif %}

{% endblock %}

templates/affairs/list/vacations.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    <br><h4> الشهور</h4>
  <form method="GET" class="contact-form" style="width:45%; align:center; margin: 0 auto; margin-top:35px;  direction: rtl;">
       <h4 style="text-align:center;">{{ title }}</h4>
       {{ form.as_p }}
       <div class="d-grid" style="margin-top:10px; ">
           <button class="btn btn-dark btn-lg " id="submitButton" type="submit">بحث</button>
         <a href="{% url 'affairs:vacations_creation' %}" class="btn btn-dark btn-lg" style="direction: ltr; display: inline; left: 10px;">
               اضافة
               <img src="{% static 'admin/img/icon-addlink.svg' %}" style="height10px; width10px">
           </a>
       </div>
    </form>

    {% if vacations %}
    <table class="table table-striped" style="width:45%; align:center; margin: 0 auto; margin-top:65px;  direction: rtl;">
      <thead>
        <tr>
          <td>الاسم</td>
          <td>من</td>
          <td>الي</td>
          <td>المدة بالايام</td>
          <td>المزيد</td>
        </tr>
      </thead>
      <tbody>
      {% for vacation in vacations %}
        <tr>
          <td scope="row">{{ vacation.worker }}</td>
          <td>{{ vacation.start_date }}</td>
          <td>{{ vacation.end_date }}</td>
          <td>{{ vacation.duration_in_days }}</td>
          <td><a href="{{ vacation.get_absolute_url }}"> المزيد </a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    {% endif %}

{% endblock %}