accounts/urls.py
from django.urls import path

from .views import (RegistrationView, LogInView, LogOutView, UserCreationView, UserDetailView,
                    WorkerCreationView, WorkerDetailView, WorkerListView, UserListView, UserChangePasswordView)

app_name = 'accounts'


urlpatterns = [
    path('login/', LogInView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),

    path('user-list/', UserListView.as_view(), name='user_list'),
    path('user-creation/', UserCreationView.as_view(), name='user_creation'),
    path('user-detail/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('user-change-password/<int:pk>/', UserChangePasswordView.as_view(), name='user_change_password'),

    path('worker-list/', WorkerListView.as_view(), name='worker_list'),
    path('worker-creation/', WorkerCreationView.as_view(), name='worker_creation'),
    path('worker-detail/<int:pk>/', WorkerDetailView.as_view(), name='worker_detail'),
]

affairs/urls.py
from django.urls import path

from reports.urls import urlpatterns as main_repo_urls
from .views import (home, MonthCreationView, MonthDetailView, MonthListView, MonthDayInlineView,
                    ActivityCreationView, ActivityDetailView, ActivityDeleteView,  ActivityListView,
                    LocationCreationView, LocationDetailView, LocationDeleteView, LocationListView,
                    VacationsCreationView, VacationsDetailView, VacationsListView,
                    validate_month_uniqueness)


app_name = 'affairs'


urlpatterns = [
    path('', home, name='home'),
    *main_repo_urls,

    path('month-list/', MonthListView.as_view(), name='month_list'),
    path('month-creation/', MonthCreationView.as_view(), name='month_creation'),
    path('month-detail/<int:pk>/', MonthDetailView.as_view(), name='month_detail'),
    path('month-day-inline/<int:pk>', MonthDayInlineView.as_view(), name='month_day_inline'),

    path('activity-list/', ActivityListView.as_view(), name='activity_list'),
    path('activity-creation/', ActivityCreationView.as_view(), name='activity_creation'),
    path('activity-detail/<int:pk>/', ActivityDetailView.as_view(), name='activity_detail'),
    path('activity-delete/<int:pk>/', ActivityDeleteView.as_view(), name='activity_delete'),

    path('location-list/', LocationListView.as_view(), name='location_list'),
    path('location-creation/', LocationCreationView.as_view(), name='location_creation'),
    path('location-detail/<int:pk>/', LocationDetailView.as_view(), name='location_detail'),
    path('location-delete/<int:pk>/', LocationDeleteView.as_view(), name='location_delete'),

    path('vacations_list/', VacationsListView.as_view(), name='vacations_list'),
    path('vacations-creation/', VacationsCreationView.as_view(), name='vacations_creation'),
    path('vacations-detail/<int:pk>/', VacationsDetailView.as_view(), name='vacations_detail'),

    path('month_uniqueness/', validate_month_uniqueness, name='month_uniqueness'),
]

reports/urls.py
from django.urls import path
from .views import (MultiWorkerReportView, AccommodationReportView, MultiWorkerReportPrintView,
                    SingleMonthReportView, SingleMonthReportPrintView, LocationReportView)


urlpatterns = [
    path('multi-worker-report/', MultiWorkerReportView.as_view(), name='multi_worker_report'),
    path('multi-worker-report-print/', MultiWorkerReportPrintView.as_view(), name='multi_worker_report_print'),

    path('single-month-report/', SingleMonthReportView.as_view(), name='single_month_report'),
    path('single-month-report-print/<int:pk>/', SingleMonthReportPrintView.as_view(), name='single_month_report_print'),

    path('accommodation-report/', AccommodationReportView.as_view(), name='accommodation_report'),

    path('location-report/', LocationReportView.as_view(), name='location_report'),
]

techno_art/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('affairs.urls', namespace='affairs')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>{% block title %} Techno Art {% endblock %}</title>
        <meta charset="UTF-8">
        <link rel="icon" type="image/x-icon" href="{% static 'images/logo_white.jpeg' %}">
        {% include 'base/css.html' %}
        {% block extra_style %} {% endblock %}
    </head>
    <body>
        <!-- Nav -->
        {% include 'base/nav.html' %}

        <!-- Content -->
        <div id="page-container" style="min-height:100vh;">
            {% include 'base/messages.html' %}
		    {% block content %}
		    {% endblock %}
        </div>

        <!-- FOOTER -->
        {% include 'base/footer.html' %}

        <!-- SCRIPTS -->
        {% include 'base/js.html' %}
        {% block extra_js %} {% endblock %}
    </body>
</html>

templates/base_form.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<section id="contact" data-stellar-background-ratio="0.5">
     <div class="container">
          <div class="row">
               <div class="col-md-offset-1 col-md-10 col-sm-12">
                   {% block content_form %}
                   {% endblock %}
               </div>
          </div>
     </div>
</section>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load  static %}

{% block content %}
<section id="contact" data-stellar-background-ratio="0.5" style="margin-top: 20px;">
     <div class="container">
          <div class="row">
               <div class="col-md-offset-1 col-md-10 col-sm-12">
                    <div class="jumbotron jumbotron-fluid">
                         {% if request.user.is_authenticated and request.user.is_superuser %}
                         <div class="container">
                              <h1 class="display-4" style=" ">الاقسام الرئيسية</h1>
                              <div class="card border-primary mb-3" style="max-width: 18rem; display: inline-block; margin: 20px;;">
                                   <div class="card-header" style="font-size: 25px;">الشؤون الوظيفية</div>
                                   <div class="card-body text-primary">
                                        <div class="container" style="display: inline;">
                                             <h5 class="card-title" style="display: inline; font-size: 20px;">
                                                  <a href="{% url 'affairs:month_creation' %}" style="color: #337ab7;"><img src="{% static 'admin/img/icon-addlink.svg' %}" style="height10px; width10px">
                                                       تسجيل الحضور والانصراف
                                                  </a>
                                             </h5>
                                        </div>
                                        <div class="container" style="display: inline; direction: ltr">
                                             <h5 class="card-title" style="display: inline; font-size: 20px;"> المواقع</h5>
                                             <a href="{% url 'affairs:location_creation' %}" style="display:inline"><img src="{% static 'admin/img/icon-addlink.svg' %}" style="height10px; width10px">اضافة</a>
                                             <a href="{% url 'affairs:location_list' %}"  style="display:inline"><img src="{% static 'admin/img/icon-changelink.svg' %}" style="height10px; width10px">تعديل</a>
                                        </div>
                                         {% if not request.user.activity %}
                                         <div class="container" style="display: inline; direction: ltr">
                                             <h5 class="card-title" style="display: inline; font-size: 20px;"> الانشطة</h5>
                                             <a href="{% url 'affairs:activity_creation' %}" style="display:inline"><img src="{% static 'admin/img/icon-addlink.svg' %}" style="height10px; width10px">اضافة</a>
                                             <a href="{% url 'affairs:activity_list' %}"  style="display:inline"><img src="{% static 'admin/img/icon-changelink.svg' %}" style="height10px; width10px">تعديل</a>
                                        </div>
                                        {% endif %}
                                   </div>
                              </div>
                         </div>
                         <hr style="height:2px;border-width:0;color:gray;background-color:gray">
                         <div class="card-header" style="font-size: 25px;">التقارير</div>
                         <ul>
                              <li style="display: inline; list-style: none; padding: 10px; font-size: 20px;"><a href="{% url 'affairs:accommodation_report' %}" class="btn btn-info"> الاقامات</a></li>
                              <li style="display: inline; list-style: none; padding: 10px; font-size: 20px;"><a id="report-btn" class="btn btn-info"> الرواتب</a></li>
                              <li style="display: inline; list-style: none; padding: 10px; font-size: 20px;"><a href="{% url 'affairs:activity_list' %}" class="btn btn-info"> الانشطة</a></li>
                              <li style="display: inline; list-style: none; padding: 10px; font-size: 20px;"><a href="{% url 'affairs:location_report' %}" class="btn btn-info"> المواقع</a></li>
                         </ul>
                         <hr style="height:2px;border-width:0;color:gray;background-color:gray">
                         <div class="card border-primary mb-3" style="max-width: 18rem; display: inline-block; margin: 20px;;">
                              <div class="card-header" style="font-size: 25px;">الشؤون الادارية</div>
                              <div class="card-body text-primary">
                                   {% if not request.user.activity %}
                                   <div class="container" style="display: inline;">
                                        <h5 class="card-title" style="display: inline; font-size: 20px;">الادارة</h5>
                                        <a href="{% url 'accounts:user_creation' %}"><img src="{% static 'admin/img/icon-addlink.svg' %}" style="height10px; width10px">اضافة</a>
                                        <a href="{% url 'accounts:user_list' %}"><img src="{% static 'admin/img/icon-changelink.svg' %}" style="height10px; width10px">تعديل</a>
                                   </div>
                                   {% endif %}
                                   <div class="container" style="display: inline; direction: ltr">
                                        <h5 class="card-title" style="display: inline; font-size: 20px;"> العمال</h5>
                                        <a href="{% url 'accounts:worker_creation' %}" style="display:inline"><img src="{% static 'admin/img/icon-addlink.svg' %}" style="height10px; width10px">اضافة</a>
                                        <a href="{% url 'accounts:worker_list' %}"  style="display:inline"><img src="{% static 'admin/img/icon-changelink.svg' %}" style="height10px; width10px">تعديل</a>
                                   </div>
                              </div>
                         </div>
                         {% else %}
                         <h5 class="card-title" style="display: inline; font-size: 20px;">شركة تكنو ارت للمقاولات</h5>
                         {% endif %}
                    </div>
               </div>
          </div>
     </div>
</section>

<input type="hidden" value="{% url 'affairs:multi_worker_report' %}" id="multi">
<input type="hidden" value="{% url 'affairs:single_month_report' %}" id="single">

{% endblock %}

{% block extra_js %}
<script src="{% static 'js/jquery.js' %}"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>
window.onload = function(){
     var btn = $('#report-btn');

     var div = document.createElement('div');

     var createA = document.createElement('a');
     var createAText = document.createTextNode('شهري تفصيلي لشخص واحد          ');
     createA.setAttribute('href', $('#single').val());
     createA.style.padding = '20px';
     createA.appendChild(createAText);

     var createB = document.createElement('a');
     var createBText = document.createTextNode('الرواتب لاكثر من شخص');
     createB.setAttribute('href', $('#multi').val());
     createB.style.padding = '20px';
     createB.appendChild(createBText);

     div.appendChild(createA);
     div.appendChild(createB);

     btn.on('click', function(e){
          swal({
               title: 'تقرير الرواتب',
               content: div,
               button: 'الغاء'
          });
     });
          $('#add_attendance').on('click', function(e){
          swal({
               title: 'تقرير الرواتب',
               content: div,
               button: 'الغاء'
          });
     });
};
</script>
{% endblock %}